[package]
name = "kafkaoxide-db"
version = "0.1.0"
edition = "2021"

[dependencies]
kafkaoxide-core = { workspace = true }
error-stack = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio", "macros", "migrate"] }

[dev-dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
